/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiQuizRouteImport } from './routes/api/quiz'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppGradesRouteImport } from './routes/app.grades'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppStudyRouteImport } from './routes/app.study'
import { Route as AppTutorRouteImport } from './routes/app.tutor'
import { Route as ApiVoiceSpeakRouteImport } from './routes/api/voice.speak'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice.transcribe'
import { Route as AppCommunityIndexRouteImport } from './routes/app.community.index'
import { Route as AppCommunityCourseIdRouteImport } from './routes/app.community.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizRoute = ApiQuizRouteImport.update({
  id: '/api/quiz',
  path: '/api/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyRoute = AppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const ApiVoiceSpeakRoute = ApiVoiceSpeakRouteImport.update({
  id: '/api/voice/speak',
  path: '/api/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommunityIndexRoute = AppCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityCourseIdRoute = AppCommunityCourseIdRouteImport.update({
  id: '/community/$courseId',
  path: '/community/$courseId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/api/quiz': typeof ApiQuizRoute
  '/api/tutor': typeof ApiTutorRoute
  '/app/ai': typeof AppAiRoute
  '/app/classes': typeof AppClassesRoute
  '/app/grades': typeof AppGradesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/study': typeof AppStudyRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/': typeof AppIndexRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/app/community/$courseId': typeof AppCommunityCourseIdRoute
  '/app/community/': typeof AppCommunityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/api/quiz': typeof ApiQuizRoute
  '/api/tutor': typeof ApiTutorRoute
  '/app/ai': typeof AppAiRoute
  '/app/classes': typeof AppClassesRoute
  '/app/grades': typeof AppGradesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/study': typeof AppStudyRoute
  '/app/tutor': typeof AppTutorRoute
  '/app': typeof AppIndexRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/app/community/$courseId': typeof AppCommunityCourseIdRoute
  '/app/community': typeof AppCommunityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/api/quiz': typeof ApiQuizRoute
  '/api/tutor': typeof ApiTutorRoute
  '/app/ai': typeof AppAiRoute
  '/app/classes': typeof AppClassesRoute
  '/app/grades': typeof AppGradesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/study': typeof AppStudyRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/': typeof AppIndexRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/app/community/$courseId': typeof AppCommunityCourseIdRoute
  '/app/community/': typeof AppCommunityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/api/chat'
    | '/api/quiz'
    | '/api/tutor'
    | '/app/ai'
    | '/app/classes'
    | '/app/grades'
    | '/app/onboarding'
    | '/app/planner'
    | '/app/profile'
    | '/app/progress'
    | '/app/study'
    | '/app/tutor'
    | '/app/'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/app/community/$courseId'
    | '/app/community/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/api/chat'
    | '/api/quiz'
    | '/api/tutor'
    | '/app/ai'
    | '/app/classes'
    | '/app/grades'
    | '/app/onboarding'
    | '/app/planner'
    | '/app/profile'
    | '/app/progress'
    | '/app/study'
    | '/app/tutor'
    | '/app'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/app/community/$courseId'
    | '/app/community'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/api/chat'
    | '/api/quiz'
    | '/api/tutor'
    | '/app/ai'
    | '/app/classes'
    | '/app/grades'
    | '/app/onboarding'
    | '/app/planner'
    | '/app/profile'
    | '/app/progress'
    | '/app/study'
    | '/app/tutor'
    | '/app/'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/app/community/$courseId'
    | '/app/community/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiQuizRoute: typeof ApiQuizRoute
  ApiTutorRoute: typeof ApiTutorRoute
  ApiVoiceSpeakRoute: typeof ApiVoiceSpeakRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quiz': {
      id: '/api/quiz'
      path: '/api/quiz'
      fullPath: '/api/quiz'
      preLoaderRoute: typeof ApiQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grades': {
      id: '/app/grades'
      path: '/grades'
      fullPath: '/app/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/study': {
      id: '/app/study'
      path: '/study'
      fullPath: '/app/study'
      preLoaderRoute: typeof AppStudyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tutor': {
      id: '/app/tutor'
      path: '/tutor'
      fullPath: '/app/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/voice/speak': {
      id: '/api/voice/speak'
      path: '/api/voice/speak'
      fullPath: '/api/voice/speak'
      preLoaderRoute: typeof ApiVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community/': {
      id: '/app/community/'
      path: '/community'
      fullPath: '/app/community/'
      preLoaderRoute: typeof AppCommunityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community/$courseId': {
      id: '/app/community/$courseId'
      path: '/community/$courseId'
      fullPath: '/app/community/$courseId'
      preLoaderRoute: typeof AppCommunityCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppClassesRoute: typeof AppClassesRoute
  AppGradesRoute: typeof AppGradesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppStudyRoute: typeof AppStudyRoute
  AppTutorRoute: typeof AppTutorRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCommunityCourseIdRoute: typeof AppCommunityCourseIdRoute
  AppCommunityIndexRoute: typeof AppCommunityIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppClassesRoute: AppClassesRoute,
  AppGradesRoute: AppGradesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppStudyRoute: AppStudyRoute,
  AppTutorRoute: AppTutorRoute,
  AppIndexRoute: AppIndexRoute,
  AppCommunityCourseIdRoute: AppCommunityCourseIdRoute,
  AppCommunityIndexRoute: AppCommunityIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  ApiQuizRoute: ApiQuizRoute,
  ApiTutorRoute: ApiTutorRoute,
  ApiVoiceSpeakRoute: ApiVoiceSpeakRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
